# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  test-core:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-python@v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run full test suite
        run: pytest --snapshot-warn-unused

  doc-build:
    needs: [test-core]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-python@v6.3.0
        with:
          python-version: '3.11'
      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]
      - name: Doxygen Deploy Action
        uses: Dan-Wanna-M/doxygen-github-pages-action@v0.1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/dev/html
          config_file: Doxyfile
          target_folder: ${{ github.ref_name }}/
          pre_build: |
            chmod +x docs/header_gen.sh
            ./docs/header_gen.sh ${{ github.ref_name }}
            chmod +x py_filter.sh
            export VERSION=${{ github.ref_name }}
            echo "PROJECT_NUMBER = $VERSION" >> Doxyfile
      - name: Generate index.html
        run: |
          python docs/index_gen.py --version ${{ github.ref_name }}
      - name: Update index.html
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/index/
          target_folder: index/
          clean: false

  deploy:
    needs: [test-core]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - name: Set up Python
      uses: actions/setup-python@v6.3.0
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
